### PR TITLE
cTuning foundation repositories should not contain code with non-cTuning copyright

### PR DESCRIPTION
**Pull request by gfursin**
I guess it's a glitch ;) ?

### CODE REVIEW

**Comment by psyhtest** [comment]
This repository was created and only contributed to by dividiti engineers. It initially had a cTuning copyright only. But then we had to fork it, when we'd lost write permissions to it. It was then when the copyright was updated. I guess you didn't notice this when [you pulled it](https://github.com/ctuning/ck-openvino/pull/23).

I personally don't see an issue with the dual copyright, but if you remove it, please acknowledge the contributions in some other way.

**Comment by gfursin** [comment]
You are right! My fault! Thanks for noting! I will revert to https://github.com/ctuning/ck-openvino/commit/07cd20cbac1f9d90c0c3c89fe59a1b0b5d471023 since cTuning foundation repositories can have only cTuning copyright.

**Comment by psyhtest** [comment]
I don't think that having an outdated copy at the **default** location (github.com/ctuning) will make anyone any good.

I hereby grant your permission to remove the dividiti copyright, if you please kindly acknowledge the contributors in the usual way (e.g. in `README.md`).

**Comment by gfursin** [comment]
Thank you! I need to check it. Overall, we want to minimize the number of repositories at github.com/ctuning because the cTuning foundation do not have spare resources to handle them at the moment :( .

**Comment by psyhtest** [comment]
If guess then we should remove the repo at github.com/ctuning/ck-openvino. The fork at github.com/dividiti/ck-openvino should stay intact, and become the new default.

But then we have so many other similar repositories, including ck-mlperf, ck-tensorrt, ck-armnn. Do you also want us to take care of them?

**Pull request merged**
